### ISSUE TITLE
ToDo:

### ISSUE THREAD

**Issue by Waltermelion** [Waltermelion/ABEIPROJECT#1]
-  Level !: "Run For Your Life!" substitui Level 285 https://backrooms.fandom.com/wiki/Level_!
- [ ] **_Props:_**
      - [ ] exit sign
      - [ ] macas
      - [ ] portas
- [ ] **_Sons:_**
      - [ ] "emergency noises"
      - [ ] sons de entidades
      - [ ] som passos jogador
      - [ ] sons distantes (scream, metal clang, etc..)
 - [ ] _**Entities:**_
      - [ ] modelos 3 entidades (mínimo dos mínimos)
      - [x] Animações feitas
      - [x] Animações implementadas no Unity 
 - [ ] _**Programação:**_ 
      - [x] Programar flashing red lights
      - [ ] Implementar os sons dos monstros
      - [x] Implementar os sons dos passos do jogador
      - [ ] Implementar o resto dos sons lol ( Ambiance, main menu theme, random distant sounds)
      - [x] Quando uma entidade ataca o jogador o jogador cai e o ecrã dá fade to black, aparece "You died" e "Press 'e' to try again"(usar animator para animar o jogador a morrer)
      - [ ] Quando jogador vai a uma saida, animator fade to black, load scene
- [ ] _**misc**_
      - [ ] Animar jogador (andar, correr, idle, morrer)(Animação deve ser feita à main camera em forma de headbob/sway)
